version: '3'

services:
    php:
        build:
            context: ./bucket/services/php
        restart: always
        ports:
            - 9000:9000
        volumes:
            - ./public/:/usr/share/nginx/html
            - ./bucket/services/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - mysql


    redis:
        image: "redis:alpine"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - ./bucket/services/redis:/var/lib/redis
            - ./bucket/services/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master

    nginx:
        image: nginx:1.19.3
        restart: unless-stopped
        volumes:
        - ./logs/nginx:/var/log/nginx
        - ./bucket/services/nginx/conf.d:/etc/nginx/conf.d
        - ./bucket/services/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./public/:/usr/share/nginx/html
        ports:
        - "80:80"
        - "443:443"
        depends_on:
            - php
            - redis
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    mysql:
        image: mariadb:10.7.3
        restart: always
        volumes:
            - ./bucket/services/mysql/conf.d:/etc/mysql/conf.d

        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}